### ISSUE TITLE
what do you think is needed to make this production-ready?

### ISSUE THREAD

**Issue by mnelson4** [thenbrent/WP-API-CORS#2]
I came across this because I found I needed for making some demo code for how to use api.eventespresso.com; but what do you think is needed to make this production-ready? Maybe an admin-interface for whitelisting specific domains, instead of always allowing requests from everyone?

**Comment by thenbrent** [comment]
Copy of my comment from Slack:

> The plugin as it stands is nothing like the one you’re taking about above with an admin interface for setting allowed origins, so if that’s what you mean by production, it’s a long way from that.
> The main purpose of that code was to show one way to get CORS working and to provide a quick way to test code that required CORS to be enabled (which is why its security policy is very liberal and it has no docs). Think of it more like an instructive snippet than a plugin. :smiley:

**Comment by mnelson4** [comment]
ya and I think it does a great job of showing how to get CORS working with the WP API. I'm considering contributing to this, and wanted to know what you thought it needed to get it production-ready. 
Although I'm a little surprised this hasn't gotten more attention- I would have thought the need would be greater

**Comment by mnelson4** [comment]
FYI I'm using it for demo'ing purposes here:
http://developer.eventespresso.com/tutorial/ee4-json-rest-api-code-samples/

**Comment by thenbrent** [comment]
> Although I'm a little surprised this hasn't gotten more attention

I suspect folks just find what they need to get it to work, copy/paste it in to their plugin then move on.

> I'm considering contributing to this, and wanted to know what you thought it needed to get it production-ready.

An admin UI could be a really handy feature for certain use cases. But it really depends on the use case of the plugin more so than the CORS component.

As far as minimum production ready version, assuming for now it doesn't include an admin UI, I'd say it needs to be tested/updated for WP-API v2.0 (when it's not in flux quite so much) and security audited. I'm not sure I feel comfortable releasing something that opens up CORS for all origins without big disclaimers  - some developers might not realise the implications.
