### ISSUE TITLE
FYI this works with WP API v2 too eh

### ISSUE THREAD

**Issue by mnelson4** [thenbrent/WP-API-CORS#4]
On https://github.com/thenbrent/WP-API-CORS/issues/2 you mentioned this hadn't been tested with WP API v2 (whose framework code is now in WP core 4.4). FYI that I just tested it with the Event Espresso 4 REST API (which now uses WP API v2) and WP 4.4 and it worked fine. No changes seemed necessary. So you could update the description to reflect that.

ps: Also because the WP API infrastructure is now in WP 4.4, not just in the plugin, it seems unlikely that there will be changes that will break this. (Future changes to the WP API will probably be to the endpoints, not the infrastructure now that it's in WP core)

**Comment by thenbrent** [comment]
@mnelson4 awesome thanks for letting me know. I've just updated the readme (with SHA: https://github.com/thenbrent/WP-API-CORS/commit/0d41becb56e3f3adc95658543e7f724f53f6dbdb). I've left the warnings about access from any host in though. :smile:
